server:
  port: 9004
spring:
  jmx:
    enabled: true
  config:
    import: optional:configserver:http://config-server.morrigan:8888
  cloud:
      config:
        username: root
        name: morrigan-service-registry
        password: celestial
        fail-fast: true
        retry:
          max-attempts: 100
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers:
      - kafka-broker-1.morrigan:9092
      - kafka-broker-2.morrigan:9092
      - kafka-broker-3.morrigan:9092
    producer:
      bootstrap-servers:
        - kafka-broker-1.morrigan:9092
        - kafka-broker-2.morrigan:9092
        - kafka-broker-3.morrigan:9092
logging:
  file:
    path: /var/log/morrigan