version: "1.0"

networks:
  morrigan:
    external: true
services:
  service-registry-db:
     image: postgres
     container_name: service-registry-db
     environment:
       POSTGRES_USER: morrigan
       POSTGRES_PASSWORD: morrigan
     volumes:
       - ./service-registry/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
     networks:
       - morrigan
  config-server:
    container_name: config-server
    build:
      context: config-server
      dockerfile: Dockerfile
    networks:
      - morrigan
    ports:
      - "8888:8888"
  coderun-redis:
    image: redis/redis-stack-server
    container_name: coderun-redis
    networks:
      - morrigan
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - morrigan
  kafka-broker-1:
    image: wurstmeister/kafka:latest
    container_name: kafka-broker-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper.morrigan:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "100"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-broker-1:29092,EXTERNAL://kafka-broker-1.morrigan:9092"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - morrigan
    depends_on:
      - zookeeper
  kafka-broker-2:
    image: wurstmeister/kafka:latest
    container_name: kafka-broker-2
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper.morrigan:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "100"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-broker-2:29092,EXTERNAL://kafka-broker-2.morrigan:9092"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - morrigan
    depends_on:
      - zookeeper
  kafka-broker-3:
    image: wurstmeister/kafka:latest
    container_name: kafka-broker-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper.morrigan:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "100"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-broker-3:29092,EXTERNAL://kafka-broker-3.morrigan:9092"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "service.launches:10:3, service.replies:10:3, service.heartbeats:10:3"
    networks:
      - morrigan
    depends_on:
      - zookeeper
      - kafka-broker-1
      - kafka-broker-2
  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9001:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka-broker-1.morrigan:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - kafka-broker-1
      - zookeeper
    networks:
      - morrigan
  service-registry-1:
    container_name: service-registry-1
    build:
      context: service-registry
      dockerfile: Dockerfile
    depends_on:
      - kafka-broker-3
      - service-registry-db
    networks:
      - morrigan
    ports:
      - "9006:9004"
  service-registry-2:
    container_name: service-registry-2
    build:
      context: service-registry
      dockerfile: Dockerfile
    depends_on:
      - kafka-broker-3
      - service-registry-db
    networks:
      - morrigan
    ports:
      - "9007:9004"
  service-registry-3:
    container_name: service-registry-3
    build:
      context: service-registry
      dockerfile: Dockerfile
    depends_on:
      - kafka-broker-3
      - service-registry-db
    networks:
      - morrigan
    ports:
      - "9008:9004"
  anonymous-coderun-service-1:
    container_name: anonymous-coderun-service-1
    build:
      context: anonymous-coderun-service
      dockerfile: Dockerfile
    ports:
      - "8006:8005"
    depends_on:
      - coderun-redis
      - service-registry-2
      - config-server
    networks:
      - morrigan
  anonymous-coderun-service-2:
    container_name: anonymous-coderun-service-2
    build:
      context: anonymous-coderun-service
      dockerfile: Dockerfile
    ports:
      - "8007:8005"
    depends_on:
      - coderun-redis
      - service-registry-2
      - config-server
    networks:
      - morrigan
  anonymous-coderun-service-3:
    container_name: anonymous-coderun-service-3
    build:
      context: anonymous-coderun-service
      dockerfile: Dockerfile
    ports:
      - "8008:8005"
    depends_on:
      - coderun-redis
      - service-registry-2
      - config-server
    networks:
      - morrigan
