// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coderun.proto

package ru.shanalotte.coderun.loadbalancer.grpc;

public interface CodeRunResultMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string stderr = 1;</code>
   * @return The stderr.
   */
  java.lang.String getStderr();
  /**
   * <code>string stderr = 1;</code>
   * @return The bytes for stderr.
   */
  com.google.protobuf.ByteString
      getStderrBytes();

  /**
   * <code>string stdout = 2;</code>
   * @return The stdout.
   */
  java.lang.String getStdout();
  /**
   * <code>string stdout = 2;</code>
   * @return The bytes for stdout.
   */
  com.google.protobuf.ByteString
      getStdoutBytes();
}
