// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coderun.proto

package ru.shanalotte.coderun.loadbalancer.grpc;

/**
 * Protobuf type {@code ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage}
 */
public final class CodeRunResultMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage)
    CodeRunResultMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CodeRunResultMessage.newBuilder() to construct.
  private CodeRunResultMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CodeRunResultMessage() {
    stderr_ = "";
    stdout_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CodeRunResultMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CodeRunResultMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            stderr_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            stdout_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.shanalotte.coderun.loadbalancer.grpc.Coderun.internal_static_ru_shanalotte_coderun_loadbalancer_grpc_CodeRunResultMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.shanalotte.coderun.loadbalancer.grpc.Coderun.internal_static_ru_shanalotte_coderun_loadbalancer_grpc_CodeRunResultMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage.class, ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage.Builder.class);
  }

  public static final int STDERR_FIELD_NUMBER = 1;
  private volatile java.lang.Object stderr_;
  /**
   * <code>string stderr = 1;</code>
   * @return The stderr.
   */
  @java.lang.Override
  public java.lang.String getStderr() {
    java.lang.Object ref = stderr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stderr_ = s;
      return s;
    }
  }
  /**
   * <code>string stderr = 1;</code>
   * @return The bytes for stderr.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStderrBytes() {
    java.lang.Object ref = stderr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stderr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STDOUT_FIELD_NUMBER = 2;
  private volatile java.lang.Object stdout_;
  /**
   * <code>string stdout = 2;</code>
   * @return The stdout.
   */
  @java.lang.Override
  public java.lang.String getStdout() {
    java.lang.Object ref = stdout_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stdout_ = s;
      return s;
    }
  }
  /**
   * <code>string stdout = 2;</code>
   * @return The bytes for stdout.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStdoutBytes() {
    java.lang.Object ref = stdout_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stdout_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stderr_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, stderr_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stdout_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, stdout_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stderr_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, stderr_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stdout_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, stdout_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage)) {
      return super.equals(obj);
    }
    ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage other = (ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage) obj;

    if (!getStderr()
        .equals(other.getStderr())) return false;
    if (!getStdout()
        .equals(other.getStdout())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STDERR_FIELD_NUMBER;
    hash = (53 * hash) + getStderr().hashCode();
    hash = (37 * hash) + STDOUT_FIELD_NUMBER;
    hash = (53 * hash) + getStdout().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage)
      ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.shanalotte.coderun.loadbalancer.grpc.Coderun.internal_static_ru_shanalotte_coderun_loadbalancer_grpc_CodeRunResultMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.shanalotte.coderun.loadbalancer.grpc.Coderun.internal_static_ru_shanalotte_coderun_loadbalancer_grpc_CodeRunResultMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage.class, ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage.Builder.class);
    }

    // Construct using ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      stderr_ = "";

      stdout_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.shanalotte.coderun.loadbalancer.grpc.Coderun.internal_static_ru_shanalotte_coderun_loadbalancer_grpc_CodeRunResultMessage_descriptor;
    }

    @java.lang.Override
    public ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage getDefaultInstanceForType() {
      return ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage.getDefaultInstance();
    }

    @java.lang.Override
    public ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage build() {
      ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage buildPartial() {
      ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage result = new ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage(this);
      result.stderr_ = stderr_;
      result.stdout_ = stdout_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage) {
        return mergeFrom((ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage other) {
      if (other == ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage.getDefaultInstance()) return this;
      if (!other.getStderr().isEmpty()) {
        stderr_ = other.stderr_;
        onChanged();
      }
      if (!other.getStdout().isEmpty()) {
        stdout_ = other.stdout_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object stderr_ = "";
    /**
     * <code>string stderr = 1;</code>
     * @return The stderr.
     */
    public java.lang.String getStderr() {
      java.lang.Object ref = stderr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stderr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string stderr = 1;</code>
     * @return The bytes for stderr.
     */
    public com.google.protobuf.ByteString
        getStderrBytes() {
      java.lang.Object ref = stderr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stderr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string stderr = 1;</code>
     * @param value The stderr to set.
     * @return This builder for chaining.
     */
    public Builder setStderr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stderr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string stderr = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStderr() {
      
      stderr_ = getDefaultInstance().getStderr();
      onChanged();
      return this;
    }
    /**
     * <code>string stderr = 1;</code>
     * @param value The bytes for stderr to set.
     * @return This builder for chaining.
     */
    public Builder setStderrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stderr_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object stdout_ = "";
    /**
     * <code>string stdout = 2;</code>
     * @return The stdout.
     */
    public java.lang.String getStdout() {
      java.lang.Object ref = stdout_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stdout_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string stdout = 2;</code>
     * @return The bytes for stdout.
     */
    public com.google.protobuf.ByteString
        getStdoutBytes() {
      java.lang.Object ref = stdout_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stdout_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string stdout = 2;</code>
     * @param value The stdout to set.
     * @return This builder for chaining.
     */
    public Builder setStdout(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stdout_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string stdout = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStdout() {
      
      stdout_ = getDefaultInstance().getStdout();
      onChanged();
      return this;
    }
    /**
     * <code>string stdout = 2;</code>
     * @param value The bytes for stdout to set.
     * @return This builder for chaining.
     */
    public Builder setStdoutBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stdout_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage)
  }

  // @@protoc_insertion_point(class_scope:ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage)
  private static final ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage();
  }

  public static ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CodeRunResultMessage>
      PARSER = new com.google.protobuf.AbstractParser<CodeRunResultMessage>() {
    @java.lang.Override
    public CodeRunResultMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CodeRunResultMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CodeRunResultMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CodeRunResultMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResultMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

