// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coderun.proto

package ru.shanalotte.coderun.loadbalancer.grpc;

public interface CodeRunRequestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.shanalotte.coderun.loadbalancer.grpc.CodeRunRequestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string language = 1;</code>
   * @return The language.
   */
  java.lang.String getLanguage();
  /**
   * <code>string language = 1;</code>
   * @return The bytes for language.
   */
  com.google.protobuf.ByteString
      getLanguageBytes();

  /**
   * <code>string code = 2;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 2;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string username = 3;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 3;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
