// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coderun.proto

package ru.shanalotte.coderun.loadbalancer.grpc;

public final class Coderun {
  private Coderun() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_shanalotte_coderun_loadbalancer_CodeRunRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_shanalotte_coderun_loadbalancer_CodeRunRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_shanalotte_coderun_loadbalancer_CodeRunResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_shanalotte_coderun_loadbalancer_CodeRunResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcoderun.proto\022\"ru.shanalotte.coderun.l" +
      "oadbalancer\"B\n\016CodeRunRequest\022\020\n\010languag" +
      "e\030\001 \001(\t\022\014\n\004code\030\002 \001(\t\022\020\n\010username\030\003 \001(\t\"" +
      "/\n\rCodeRunResult\022\016\n\006stderr\030\001 \001(\t\022\016\n\006stdo" +
      "ut\030\002 \001(\t2\203\001\n\017CoderunBalancer\022p\n\007runCode\022" +
      "2.ru.shanalotte.coderun.loadbalancer.Cod" +
      "eRunRequest\0321.ru.shanalotte.coderun.load" +
      "balancer.CodeRunResultB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ru_shanalotte_coderun_loadbalancer_CodeRunRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_shanalotte_coderun_loadbalancer_CodeRunRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_shanalotte_coderun_loadbalancer_CodeRunRequest_descriptor,
        new java.lang.String[] { "Language", "Code", "Username", });
    internal_static_ru_shanalotte_coderun_loadbalancer_CodeRunResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ru_shanalotte_coderun_loadbalancer_CodeRunResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_shanalotte_coderun_loadbalancer_CodeRunResult_descriptor,
        new java.lang.String[] { "Stderr", "Stdout", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
