spring:
  config:
    import: optional:configserver:http://config-server.morrigan:8888
  cloud:
      config:
        username: root
        name: morrigan-service-registry-client
        password: celestial
        fail-fast: true
        retry:
          max-attempts: 100
  kafka:
    bootstrap-servers:
      - kafka-broker-1.morrigan:9092
      - kafka-broker-2.morrigan:9092
      - kafka-broker-3.morrigan:9092
    consumer:
      auto-offset-reset: earliest
      group-id: ${random.uuid}
    producer:
      properties:
        request.timeout.ms: 1000
        delivery.timeout.ms: 2000
        max.block.ms: 5000