spring:
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
      config:
        username: root
        name: morrigan-service-registry-client
        password: celestial
        fail-fast: true
        retry:
          max-attempts: 100
  kafka:
    consumer:
      auto-offset-reset: earliest