// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coderun.proto

package ru.shanalotte.coderun.gateway.grpc;

/**
 * Protobuf type {@code ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResult}
 */
public final class CodeRunResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResult)
    CodeRunResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CodeRunResult.newBuilder() to construct.
  private CodeRunResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CodeRunResult() {
    stderr_ = "";
    stdout_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new CodeRunResult();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CodeRunResult(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            stderr_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            stdout_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Coderun.internal_static_ru_shanalotte_coderun_loadbalancer_CodeRunResult_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Coderun.internal_static_ru_shanalotte_coderun_loadbalancer_CodeRunResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CodeRunResult.class, Builder.class);
  }

  public static final int STDERR_FIELD_NUMBER = 1;
  private volatile Object stderr_;
  /**
   * <code>string stderr = 1;</code>
   * @return The stderr.
   */
  @Override
  public String getStderr() {
    Object ref = stderr_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      stderr_ = s;
      return s;
    }
  }
  /**
   * <code>string stderr = 1;</code>
   * @return The bytes for stderr.
   */
  @Override
  public com.google.protobuf.ByteString
      getStderrBytes() {
    Object ref = stderr_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      stderr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STDOUT_FIELD_NUMBER = 2;
  private volatile Object stdout_;
  /**
   * <code>string stdout = 2;</code>
   * @return The stdout.
   */
  @Override
  public String getStdout() {
    Object ref = stdout_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      stdout_ = s;
      return s;
    }
  }
  /**
   * <code>string stdout = 2;</code>
   * @return The bytes for stdout.
   */
  @Override
  public com.google.protobuf.ByteString
      getStdoutBytes() {
    Object ref = stdout_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      stdout_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stderr_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, stderr_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stdout_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, stdout_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stderr_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, stderr_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stdout_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, stdout_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CodeRunResult)) {
      return super.equals(obj);
    }
    CodeRunResult other = (CodeRunResult) obj;

    if (!getStderr()
        .equals(other.getStderr())) return false;
    if (!getStdout()
        .equals(other.getStdout())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STDERR_FIELD_NUMBER;
    hash = (53 * hash) + getStderr().hashCode();
    hash = (37 * hash) + STDOUT_FIELD_NUMBER;
    hash = (53 * hash) + getStdout().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CodeRunResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CodeRunResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CodeRunResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CodeRunResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CodeRunResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CodeRunResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CodeRunResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CodeRunResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static CodeRunResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static CodeRunResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CodeRunResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CodeRunResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CodeRunResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResult)
      CodeRunResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Coderun.internal_static_ru_shanalotte_coderun_loadbalancer_CodeRunResult_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Coderun.internal_static_ru_shanalotte_coderun_loadbalancer_CodeRunResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CodeRunResult.class, Builder.class);
    }

    // Construct using ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      stderr_ = "";

      stdout_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Coderun.internal_static_ru_shanalotte_coderun_loadbalancer_CodeRunResult_descriptor;
    }

    @Override
    public CodeRunResult getDefaultInstanceForType() {
      return CodeRunResult.getDefaultInstance();
    }

    @Override
    public CodeRunResult build() {
      CodeRunResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public CodeRunResult buildPartial() {
      CodeRunResult result = new CodeRunResult(this);
      result.stderr_ = stderr_;
      result.stdout_ = stdout_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CodeRunResult) {
        return mergeFrom((CodeRunResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CodeRunResult other) {
      if (other == CodeRunResult.getDefaultInstance()) return this;
      if (!other.getStderr().isEmpty()) {
        stderr_ = other.stderr_;
        onChanged();
      }
      if (!other.getStdout().isEmpty()) {
        stdout_ = other.stdout_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CodeRunResult parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CodeRunResult) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object stderr_ = "";
    /**
     * <code>string stderr = 1;</code>
     * @return The stderr.
     */
    public String getStderr() {
      Object ref = stderr_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        stderr_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string stderr = 1;</code>
     * @return The bytes for stderr.
     */
    public com.google.protobuf.ByteString
        getStderrBytes() {
      Object ref = stderr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        stderr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string stderr = 1;</code>
     * @param value The stderr to set.
     * @return This builder for chaining.
     */
    public Builder setStderr(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stderr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string stderr = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStderr() {
      
      stderr_ = getDefaultInstance().getStderr();
      onChanged();
      return this;
    }
    /**
     * <code>string stderr = 1;</code>
     * @param value The bytes for stderr to set.
     * @return This builder for chaining.
     */
    public Builder setStderrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stderr_ = value;
      onChanged();
      return this;
    }

    private Object stdout_ = "";
    /**
     * <code>string stdout = 2;</code>
     * @return The stdout.
     */
    public String getStdout() {
      Object ref = stdout_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        stdout_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string stdout = 2;</code>
     * @return The bytes for stdout.
     */
    public com.google.protobuf.ByteString
        getStdoutBytes() {
      Object ref = stdout_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        stdout_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string stdout = 2;</code>
     * @param value The stdout to set.
     * @return This builder for chaining.
     */
    public Builder setStdout(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stdout_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string stdout = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStdout() {
      
      stdout_ = getDefaultInstance().getStdout();
      onChanged();
      return this;
    }
    /**
     * <code>string stdout = 2;</code>
     * @param value The bytes for stdout to set.
     * @return This builder for chaining.
     */
    public Builder setStdoutBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stdout_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResult)
  }

  // @@protoc_insertion_point(class_scope:ru.shanalotte.coderun.loadbalancer.grpc.CodeRunResult)
  private static final CodeRunResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CodeRunResult();
  }

  public static CodeRunResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CodeRunResult>
      PARSER = new com.google.protobuf.AbstractParser<CodeRunResult>() {
    @Override
    public CodeRunResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CodeRunResult(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CodeRunResult> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<CodeRunResult> getParserForType() {
    return PARSER;
  }

  @Override
  public CodeRunResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

