spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dmitriydb/morrigan-language
  security:
    user:
      name: root
      password: celestial
  application:
    name: morrigan-config-server
server:
  port: 8888